version: 2.0
jobs:
  - build_server_pdfs: # << the job to conditionally run based on the filter-by-branch-name.
      filters:
        branches:
          only: /feature\/.*/

  build:

    working_directory: ~/MobiquityRestAssuredAssignment

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:

          key: MobiquityRestAssuredAssignment-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: MobiquityRestAssuredAssignment-{{ checksum "pom.xml" }}

      - run: mvn clean verify

      - store_test_results:
          path: reports

      - store_artifacts:
          path: reports