version: 2
jobs:
  build:

    working_directory: ~/RestAssuredWithCircleci

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:

          key: RestAssuredWithCircleci-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: RestAssuredWithCircleci-{{ checksum "pom.xml" }}

      - run: mvn clean test -Dtest=VerifyUserService,VerifyPostService,Verif*EmailService,VerifyEmailID -DreTry=2

      - store_test_results:
          path: reports

      - store_artifacts:
          path: reports